import Link from "next/link";
export const metadata = { title: "How it works" };
export default function Guide() {
  return <main id="main" className="reading-page"><span className="eyebrow">YOUR STUDY ROUTINE</span><h1>From a passage<br />to daily practice.</h1><p className="lead">Prepare your material on a bigger screen. Make each line manageable. Come back to practise whenever you have a few minutes.</p>
    <section><h2>1. Bring something you want to learn</h2><p>Upload a UTF-8 .txt, .md or .json lesson file, or paste text from your notes, a document or an article. Choose Japanese or English. For PDF and Word files, copy and paste the text first. Image scans need text recognition before import.</p><p>Each lesson supports up to 60,000 source characters and 200 practice lines. Text and lesson files must be under 256 KB.</p></section>
    <section><h2>2. Make it your lesson</h2><p>Add a title, a topic and an optional level. Preview the suggested lines and edit, split, combine or remove them. Add meanings or speaker names when helpful. Levels are your own labels; the site does not assess your proficiency or generate translations.</p></section>
    <section><h2>3. Listen, repeat and review</h2><p>Open a saved lesson and practise one line at a time. Listen at a normal or slower speed, reveal your notes, and mark the line as practised. Your library and progress are saved in this browser only; clearing browser data removes them. Download lessons as a backup.</p><p>Listening uses your browser’s speech provider and available language voices. Some providers use the network. On Android, install an offline Japanese or English voice for offline reference listening.</p></section>
    <section id="android"><h2>4. Take your lessons to Android</h2><p>Use <strong>Send to Android</strong> to create a private link valid for 48 hours. In the updated Android app, open <strong>My materials → Import companion link</strong> and paste the link, then choose <strong>Download and preview</strong>. Anyone with the link can read the lesson, so share it only with people you intend to receive it.</p><p>Alternatively, download the lesson JSON, move it to your phone, and select it in <strong>My materials → Import from Drive or phone</strong>. The app previews it before you save. Japanese lessons from older app versions remain supported. English and website links require app version 0.4.0 or later.</p><p>Website and Android libraries are separate. Transferring a lesson does not synchronize subsequent edits or practice progress. Audio recordings stay on your phone.</p><p>The Android app is currently a development pilot, not a Play Store release. Install the updated APK supplied with this project.</p></section>
    <Link href="/" className="primary button-link">Back to the study desk</Link>
  </main>;
}
